const { determineCategory } = require('./lib/classification');
const { defaultBusinessRules } = require('./lib/business-rules.shared');

// Try to use the fetched rules just like the app would
const rules = {
  keywordRules: {
    cssKeywords: ["security assessment", "pentest", "penetration", "vapt", "vulnerability", "bulk mandays pentest", "bulkmandays pentest", "annual penetration", "email phishing", "audit dan pentest", "third party assesment", "third party assessment", "vendor assessment", "pluxee", "soc", "siem", "managed service soc", "managed services soc", "soar", "threat intel", "managed service cybersecurity", "renewal support project it", "audit it", "audit governance", "audit surveillance", "audit", "proxy", "iso 27001", "iso27001", "resertifikasi", "sertifikasi iso", "certif", "tata kelola keamanan siber", "pam", "cyberark", "krontech", "iam", "identity access", "privilege identity", "falaina", "certificate lifecycle", "krmc", "kanguru", "bigfix", "nessus", "fortify", "sast", "sca", "dast", "tenable", "burp", "acunetix", "titus", "trellix", "axonius", "solarwind", "sangfor", "imperva", "waf", "cwaf", "firewall", "dspm", "dynatrace", "hcl bigfix", "hcl", "microfocus fortify", "license nessus", "server", "san switch", "huawei storage", "microsoft server", "managed service m365", "patch management", "hardening", "mobile security", "itam", "it asset", "security awareness", "training security", "project license", "renewal bigfix", "renewal microfocus", "renewal license hcl", "renewal license nessus", "renewal license tenable", "renewal license burp", "license sast", "bigfix compliance", "license & support", "renewal license", "renewal proxy", "renewal siem", "upgrade siem", "blackberry workspace", "blackberry workspaces", "blackberry", "bussan auto finance", "va", "va bulk", "project manager bau", "privileged access management"], 
    fccKeywords: ["aml", "anti-money laundering", "actimize", "gro", "wlf", "sam9", "sam 9", "goaml", "go-aml", "fds", "corporate fraud", "watchlist", "screening", "barista", "gowap", "onesumx", "antasena", "cr-one", "crone", "iclips", "ats database", "ats cr", "ats maintenance", "loyalty system", "bcas loyalty", "sungl", "egls", "pocketbank", "digicash", "lkpbu", "jboss bri", "los", "loan origination", "lto", "mufg", "btpn", "cr paynet", "cr tcj", "cr mcca", "cr book", "cr resizing", "cr update", "cr travel", "cr enhancement gro", "cr adjustment", "enhancement gro", "cr supply chain", "cr murabahah", "cr treatment", "cr gl", "cr split unhold", "cr iga", "cr enhancement etl", "cr digital operational excellence", "cr penambahan originating", "lcr nsfr", "frtb", "treasury alm", "treasury dan alm", "risk modelling", "qnb rwa", "lld", "dhe", "middleware retail treasury", "tis", "bulk disbursement", "dcash", "dwallet", "d wallet", "gl engine", "restruktur", "swift mx", "swift release mx", "retail banking local maintenance support", "corporate banking local maintenance support", "onsite support jsl", "renewal ams iclips", "ams iclips", "maintenance jboss", "post implementation project", "jasa local support lcr", "enhancement swift release mx", "correspondent banking", "cimb berhad fa", "cimb berhad", "book of octo", "renewal ifmx", "cr enhancement"], 
    strictCssKeywords: ["pentest", "penetration", "vapt", "vulnerability", "phishing", "powertech", "data loss prevention", "dlp", "forcepoint", "fazpass", "ciphertrust", "identity government"], 
    strictFccKeywords: ["ifmx", "fraud", "cimb bank berhad", "cimb bank berhard", "garuda", "virtual account", "va bni", "va bri", "va mandiri", "va bca"]
  },
};

const row1 = { PROJECT_NAME: "Pentest QRIS CPM" };
const row2 = { PROJECT_NAME: "Pentest Audit Virtual Account" };

console.log("Pentest QRIS CPM =>", determineCategory(row1, rules));
console.log("Pentest Audit Virtual Account =>", determineCategory(row2, rules));
